/*===========================================================================

   Copyright (c) neuron Inc. 2012-
   All rights reserved.
   Author: Chen Zeshi, Scott  

=============================================================================*/

#ifndef APPLICATION_INFO_H
#define APPLICATION_INFO_H

#include <boost/preprocessor/stringize.hpp>

/*
 * AUTO-GENERATION WARNING:
 *     This file has been automatically generated from "ApplicationInfo.h.in.cmake".
 *     DO NOT edit this file, as any changes will be automatically discarded.
 */

#undef APPLICATION_NAME
#undef APPLICATION_CODENAME
#undef APPLICATION_COPYRIGHT_YEARS    
#undef APPLICATION_VERSION_MAJOR
#undef APPLICATION_VERSION_MINOR      
#undef APPLICATION_VERSION_PATCH
#undef APPLICATION_VERSION_TYPE  
#undef APPLICATION_VERSION_STRING     
#undef APPLICATION_VENDOR_ID          
#undef APPLICATION_VENDOR_NAME        
#undef APPLICATION_VENDOR_URL         
#undef APPLICATION_ID                 
 
#define APPLICATION_NAME               "Quince Sketch"
#define APPLICATION_CODENAME           "QuinceSketch"
#define APPLICATION_COPYRIGHT_YEARS    "2012"
#define APPLICATION_VERSION_MAJOR      1
/* #undef APPLICATION_VERSION_MINOR */
/* #undef APPLICATION_VERSION_PATCH */
#define APPLICATION_VERSION_TYPE       "SNAPSHOT"
#define APPLICATION_VERSION_STRING     "1.0.0-SNAPSHOT"
#define APPLICATION_VENDOR_ID          "com.neuron"
#define APPLICATION_VENDOR_NAME        "neuron Inc"
#define APPLICATION_VENDOR_URL         "www.neuron.com"
#define APPLICATION_ID                 "com.neuron"

#ifndef APPLICATION_NAME
#   error "Please specify the application name in the CMakeLists.txt file."
#endif

#ifndef APPLICATION_CODENAME
#   error "Please specify the application codename in the CMakeLists.txt file."
#endif

#ifndef APPLICATION_COPYRIGHT_YEARS
#   error "Please specify the application copyright years (years during which this application was created, edited, or modified) in the top-level CMakeLists.txt file."
#endif

#ifndef APPLICATION_VERSION_MAJOR
#   define APPLICATION_VERSOIN_MAJOR 0
#endif

#ifndef APPLICATION_VERSION_MINOR
#   define APPLICATION_VERSION_MINOR 0
#endif

#ifndef APPLICATION_VERSION_PATCH
#   define APPLICATION_VERSION_PATCH 0
#endif

#ifndef APPLICATION_VERSION_TYPE
#   define APPLICATION_VERSION_TYPE "SNAPSHOT"
#endif

#ifndef APPLICATION_VERSION_STRING
#   define APPLICATION_VERSION_STRING BOOST_PP_STRINGIZE(APPLICATION_VERSION_MAJOR) "." BOOST_PP_STRINGIZE(APPLICATION_VERSION_MINOR) "." BOOST_PP_STRINGIZE(APPLICATION_VERSION_PATCH) "-" APPLICATION_VERSION_TYPE
#endif

#ifndef APPLICATION_VENDOR_ID
#   error "Please specify the application vendor id in the CMakeLists.txt file."
#endif

#ifndef APPLICATION_VENDOR_NAME
#   error "Please specify the application vendor name in the CMakeLists.txt file."
#endif

#ifndef APPLICATION_VENDOR_URL
#   error "Please specify the application vendor URL in the CMakeLists.txt file."
#endif

#ifndef APPLICATION_ID
#   define APPLICATION_ID APPLICATION_VENDOR_ID "." APPLICATION_CODENAME
#endif

#endif
